//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barcode
    {
        public string Model { get; set; }
        public string OptionCode { get; set; }
        public string Vehicle { get; set; }
        public string ACUCode { get; set; }
        public string CLUCode { get; set; }
        public string ModelCode { get; set; }
        public string CarName { get; set; }
    }
}
