//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QTSX
    {
        public string Vin_Code { get; set; }
        public string Model { get; set; }
        public string LotNo { get; set; }
        public string Tranmission { get; set; }
        public Nullable<bool> BodyPrinted { get; set; }
        public Nullable<System.DateTime> DayBodyPrinted { get; set; }
        public Nullable<bool> AssemblyPrinted { get; set; }
        public Nullable<System.DateTime> DayAssemblyPrinted { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> DataImport { get; set; }
        public string Color { get; set; }
        public string NoEngine { get; set; }
        public string LotEn { get; set; }
        public string Kien { get; set; }
        public Nullable<System.DateTime> TimeSub { get; set; }
    }
}
