//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanCount
    {
        public int ID_ScanCount { get; set; }
        public string VinCode { get; set; }
        public string Station { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
